### ISSUE TITLE
Getting user location doesn't seems to work on iOS9

### ISSUE THREAD

**Issue by npjk** [malcommac/SwiftLocation#118]
Hello,

When I try to retrieve user location on iOS9, the request is added to the queue but then nothing happens. You can reproduce this in the simulator with the sample project by using the first commented case :
```
let x = Location.getLocation(accuracy: .city, frequency: .continuous, success: { (_, location) in
	print("A new update of location is available: \(location)")
}) { (request, last, error) in
	request.cancel() // stop continous location monitoring on error
	print("Location monitoring failed due to an error \(error)")
}
x.register(observer: LocObserver.onAuthDidChange(.main, { (request, oldAuth, newAuth) in
	print("Authorization moved from \(oldAuth) to \(newAuth)")
}))
```

It works on iOS10 sim but not on iOS9 (same on devices).
I tried many configurations but it doesn't seems to change anything.

**Comment by malcommac** [comment]
Have you added `NSLocationWhenInUseUsageDescription` or `NSLocationAlwaysUsageDescription` in your apo's `Info.plist`?
(Don't use `NSLocationUsageDescription` because it's deprecated)

**Comment by npjk** [comment]
Yes (and it is also in the sample project)

**Comment by npjk** [comment]
Hum, it seems that I messed up with versions in my first post (edited) but, just to be clear : it works on iOS10 but not on iOS9

**Comment by malcommac** [comment]
Just tried with 9.3.5 and it works fine.
Then only problem I can't get notifications about auth changes.
Is the app requests to you auth to get the location at startup?

**Comment by malcommac** [comment]
Meanwhile I've fixed the dispatch of auth events (https://github.com/malcommac/SwiftLocation/commit/ef557ae1713fe9a1bef5851ffaeafa062800804e)

**Comment by npjk** [comment]
Yes, it requests auth but that's it.

**Comment by npjk** [comment]
I tried the develop branch, now, I get notified when Auth changes but I'm still not getting anything after that.

![screen shot 2017-04-05 at 10 27 10 am](https://cloud.githubusercontent.com/assets/7323838/24696774/ecd8ac3c-19ea-11e7-9ab2-3f14d37168d0.png)

**Comment by npjk** [comment]
I manage to get (just now) an iPhone running on iOS9 and it works fine on it... so I don't know... could it be a bug occuring only on my iOS9 sim ?

**Comment by malcommac** [comment]
What a strange thing :-)
Tell me if you encounter something else.
I'll close it right now.
Just released 2.0.2 on cocoapods.
