### ISSUE TITLE
ISSUE: Library not loaded: @rpath/SwiftyJSON.framework

### ISSUE THREAD

**Issue by Lennartbrugger** [malcommac/SwiftLocation#194]
I did't get error from Xcode - Yeah.
But tbh my application crashes every time before it could even start and this is the abortion-message I get:

```
dyld: Library not loaded: @rpath/SwiftyJSON.framework/SwiftyJSON
  Referenced from: /private/var/containers/Bundle/Application/xyz/myapp.app/Frameworks/SwiftLocation.framework/SwiftLocation
  Reason: image not found
```

How can this issue be fixed? 
Help would be very appreciated!

**Comment by federicopolesello** [comment]
Hi @Lennartbrugger!
Did you solve the issue? It happens to me too!
I installed it via Carthage and imported like the other libraries.
Thanks

**Comment by DrAma999** [comment]
Just add SwiftyJSON in you cartfile and add the framework to your project.

**Comment by Lennartbrugger** [comment]
@poledeveloper Yes. I fixed the issue 👍 

You have to run following steps:

1. In the project navigator, select your project.
2. Select your target.
3. Select the "Build Phases" tab.
4. Open "Link Binaries With Libraries" expander.
5. Click the + button.
6. Select your framework.
7. Set Framework settings to "optional"

**Comment by federicopolesello** [comment]
@Lennartbrugger thanks but your solution doesn't work for me.
I resolved with @DrAma999 solution.

**Comment by malcommac** [comment]
Thanks for report. I'll close it.

**Comment by dianamelita** [comment]
I'm getting this issue as well, I tried all the solutions above (and more) but I'm still getting the error: 
dyld: Library not loaded: @rpath/RxAtomic.framework/RxAtomic
Reason: no suitable image found.

Did anyone find any solution to this? I'm using cocoapods.
