### ISSUE TITLE
does not handle authorization correctly

### ISSUE THREAD

**Issue by tcurdt** [malcommac/SwiftLocation#50]
Run this snippet, then decline on the location authorization:

```
Location.getLocation(withAccuracy: .Block, onSuccess: { foundLocation in
}) { (lastValidLocation, error) in
}
```

you will get back an error saying `Authorization did change`.

Run it again and neither closure is called. So no "onSuccess" and no error.

That is quite broken.

**Comment by malcommac** [comment]
I've tried with your code snippet.
In fact the error is correct; error is related to auth level set by user. In this case you will see a .Denied auth error.
Something like:

``` swift
Location.getLocation(withAccuracy: .Block, onSuccess: { (location) in
    // location found
}) { (last, error) in
    switch error {
        case .AuthorizationDidChange(let status):
            // oh oh auth problem: status is CLAuthorizationStatus
        case ...
    }
}
```

However in order to be more clear I've also implemented CustomStringConvertible in CLAuthorizationStatus (it will be part of the 1.0.1 update)-
See this commit https://github.com/malcommac/SwiftLocation/commit/aea553f5f0e66a99547d7b6d6d1399d8e5aa3e1a
So if you try to print error in this case you will get:
`"Failed due to user auth status: 'User Denied'"`

**Comment by tcurdt** [comment]
@malcommac you missed the actual bug :) It's not about the unclear message.

After calling it a second time neither closure is getting called. No `onSuccess` and no `onError`.

**Comment by malcommac** [comment]
Another time mean "another cold-startup of the app"?

**Comment by tcurdt** [comment]
No, it means calling it twice in the same app "session".

**Comment by tcurdt** [comment]
Literally this

```
Location.getLocation(withAccuracy: .Block, onSuccess: { foundLocation in
  print("1")
}) { (lastValidLocation, error) in
  print("1")
}
Location.getLocation(withAccuracy: .Block, onSuccess: { foundLocation in
  print("2")
}) { (lastValidLocation, error) in
  print("2")
}
```

should reproduce the problem. You will only get "1" not "2".

**Comment by malcommac** [comment]
Have you tried with 1.0.1?
I can't reproduce it both at first auth request or subsequent startups

![image](http://i.imgur.com/rhRmiwJ.png)

**Comment by tcurdt** [comment]
OK. That's super odd. I was trying with 1.0.0. Not sure what changes in the setup we have/had. iOS Version? Simulator vs device? No idea. Could you maybe zip up your test project and attach it to the issue? Maybe I could give it a try.

I found that `requestWhenInUseAuthorization` does not always cause a call to `didChangeAuthorizationStatus` (or didFail) - hence the lack of a callback.

I ended up writing a LocationManager that is a little simpler and a little more focused to what I need - and it works fine here now.

I am super sure this is/was a problem in 1.0.0 at least (for me). I assume it should be an easy fix for `SwiftLocation`, too. I would love to help but I am not sure I have the cycles for a PR at the moment. Thought you should be aware though.
